matrix:
  include:
    - language: ruby
      rvm: 2.4.1
      before_script: gem install awesome_bot
      script: awesome_bot --allow-redirect --alow-ssl --allow-dupe README.md

    - language: node_js
      node_js: 'node'
      before_script: npm install awesome-lint

notifications:
  email: false
